apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-workflows.git
    targetRevision: v3.4.17 # Safe fallback or latest 3.x if needed, let's use v3.5.5 based on the pod version in logs!
    path: manifests/base/crds/full
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
