apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-databases
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/felipefrocha/skaffold-init.git
    targetRevision: main
    path: k8s/databases
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
