apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-idp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: https://github.com/felipefrocha/skaffold-init.git
      targetRevision: main
      chart: dex
      helm:
        valueFiles:
          - $values/helm/dex-values.yaml
    - repoURL: https://github.com/felipefrocha/skaffold-init.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
