apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/kagent-dev/kagent/helm
    targetRevision: 1.0.0 # Will grab latest matching matching if not specific. Wait, OCI needs specific? 0.1.0 as dummy, user needs to specify or it's implicitly latest if omitted? OCI helm charts usually need targetRevision. Let's omit if possible, or use 0.1.0 as placeholder.
    # Helm OCI charts require a targetRevision. 
    # The setup script didn't pass a version, so it used latest. 
    # Let's put a placeholder, or maybe we don't know the exact version. 
    # Actually, let's use '*' or just let it fail if missing and user can fix.
    chart: kagent-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
