apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/felipefrocha/skaffold-init.git
      chart: kagent
      # OCI targetRevision omitted, will it pull latest? We usually need to specify it. 
      # Since we don't have it, let's assume it resolves if omitted, or '*' works.
      targetRevision: main
      helm:
        valueFiles:
          - $values/helm/kagent-values.yaml
    - repoURL: https://github.com/felipefrocha/skaffold-init.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
